# This workflow will deploy the Fixie Examples to Fixie, as the "Fixie" user.

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up credentials file
      run: echo '${{secrets.GCP_SA_KEY}}' > ./service_account.json

    - name: Deploy agents
      run: |
        ./scripts/deploy.sh
